on:
  push:
    branches:
      - develop

name: Auto Deploy to AWS Lambda

jobs:
  deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x' (사용하는 node 버전)

      - name: Install Dependencies
        run: |
          npm install -g serverless@3.39.0 
          npm install
      - name: Deploy to Lambda
        run: sls deploy 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}